import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');
let failed=false;
const check=(label,ok)=>{console.log(`${ok?'PASS':'FAIL'}: ${label}`);if(!ok)failed=true};
const version=JSON.parse(read('public/master-version.json'));
const master=read('public/reader-master-fixes.js');
const tools=read('public/reader-tools.css');
const reader=read('public/reader.html');
const manifest=read('public/manifest.webmanifest');
check('master version is 35.0.0',version.version==='35.0.0');
check('tool-sheet participates in runtime scroll surfaces',master.includes("'.tool-sheet'"));
check('tool-sheet is a primary active overlay scroller',master.includes("'.tool-shade.on .tool-sheet'"));
check('form controls are skipped as gesture scroll owners',master.includes("textarea,input,select,[contenteditable=\"true\"]"));
check('track list remains an explicit nested scroller',master.includes('.track-list'));
check('tool sheet has explicit iPhone height',tools.includes('Master v35 — unified iPhone tool-sheet scrolling'));
check('tool sheet has vertical overflow',tools.includes('overflow-y:auto!important'));
check('tool sheet has touch momentum',tools.includes('-webkit-overflow-scrolling:touch!important'));
check('card text cannot monopolize the whole screen',tools.includes('#cardText{max-height:34dvh'));
check('reader loads v35 assets',reader.includes('?v=35'));
check('PWA starts at v35',manifest.includes('"start_url": "/reader.html?v=35"'));
check('auto scroll still instant',reader.includes("behavior:'instant'"));
check('modified chapter 46 remains present',/"no"\s*:\s*46/.test(reader));
if(failed)process.exit(1);
console.log('v35 modal/tool-sheet scroll regression checks passed.');
